//
// Created by michael on 2017-04-05.
//

#ifndef INC_3DCOPY_ICP_DID_NOT_CONVERGE_EXCEPTION_H
#define INC_3DCOPY_ICP_DID_NOT_CONVERGE_EXCEPTION_H


class ICP_DID_NOT_CONVERGE_EXCEPTION {

};


#endif //INC_3DCOPY_ICP_DID_NOT_CONVERGE_EXCEPTION_H
